/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "uoqhfnxaqbnlhwasnmlx"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvcWhmbnhhcWJubGh3YXNubWx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MjAxOTUsImV4cCI6MjA2NDM5NjE5NX0.vqI9TtTrJzV6C6TfNL-NUxd2ErSQQ-ThCefhNBfzNsM"